-- ========================================
-- 1. XÓA BẢNG AN TOÀN
-- ========================================
BEGIN
    FOR t IN (SELECT table_name FROM user_tables
              WHERE table_name IN ('CHITIETNHAPHANG','DONNHAPHANG','CHITIETDONHANG','DONHANG',
                                   'KHACHHANG','HOA','LOAIHOA','NHANVIEN','CHUCVU','KHO','CHINHANH'))
    LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/
-- ========================================
-- 2. TẠO BẢNG – ĐÃ CẬP NHẬT MỐI QUAN HỆ CHINHANH ↔ DONHANG
-- ========================================

-- 1. CHINHANH
CREATE TABLE CHINHANH (
    MaChiNhanh CHAR(10) PRIMARY KEY,
    TenChiNhanh NVARCHAR2(100) NOT NULL,
    DiaChi_CN NVARCHAR2(200) NOT NULL,
    SDT_CN VARCHAR2(15) NOT NULL,
    CONSTRAINT CHK_CN_SDT CHECK (REGEXP_LIKE(SDT_CN, '^0[0-9]{9,10}$'))
);

-- 2. KHO (thuộc chi nhánh)
CREATE TABLE KHO (
    MaKho CHAR(10) PRIMARY KEY,
    TenKho NVARCHAR2(100) NOT NULL,
    MaChiNhanh CHAR(10) NOT NULL,
    CONSTRAINT FK_KHO_CN FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh)
);

-- 3. CHUCVU
CREATE TABLE CHUCVU (
    MaCV CHAR(10) PRIMARY KEY,
    TenCV NVARCHAR2(100) NOT NULL
);

-- 4. NHANVIEN (làm việc tại chi nhánh)
CREATE TABLE NHANVIEN (
    MaNV CHAR(10) PRIMARY KEY,
    TenNV NVARCHAR2(100) NOT NULL,
    NamSinh NUMBER(4) NOT NULL,
    MaCV CHAR(10) NOT NULL,
    MaChiNhanh CHAR(10) NOT NULL,
    CONSTRAINT FK_NV_CV FOREIGN KEY (MaCV) REFERENCES CHUCVU(MaCV),
    CONSTRAINT FK_NV_CN FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh)
);

-- 5. LOAIHOA
CREATE TABLE LOAIHOA (
    MaLoaiHoa CHAR(10) PRIMARY KEY,
    TenLoaiHoa NVARCHAR2(100) NOT NULL
);

-- 6. HOA
CREATE TABLE HOA (
    MaHoa CHAR(10) PRIMARY KEY,
    TenHoa NVARCHAR2(100) NOT NULL,
    MoTa NVARCHAR2(255),
    DonGiaHoa NUMBER(10,2) NOT NULL,
    MaLoaiHoa CHAR(10) NOT NULL,
    CONSTRAINT FK_HOA_LOAI FOREIGN KEY (MaLoaiHoa) REFERENCES LOAIHOA(MaLoaiHoa),
    CONSTRAINT CHK_HOA_DONGIAHOA CHECK (DonGiaHoa > 0)
);

-- 7. KHACHHANG
CREATE TABLE KHACHHANG (
    MaKH CHAR(10) PRIMARY KEY,
    HoTen NVARCHAR2(100) NOT NULL,
    DiaChi NVARCHAR2(200) NOT NULL,
    SDT_KH VARCHAR2(15) NOT NULL,
    NgaySinh DATE,
    CONSTRAINT CHK_KH_SDT CHECK (REGEXP_LIKE(SDT_KH, '^0[0-9]{9}$'))
);

-- 8. DONHANG (THÊM MaChiNhanh + FK)
CREATE TABLE DONHANG (
    MaDH CHAR(10) PRIMARY KEY,
    NgayDat DATE DEFAULT SYSDATE NOT NULL,
    NgayGiao DATE,
    TrangThai VARCHAR2(20) DEFAULT 'CHO XAC NHAN' NOT NULL,
    MaKH CHAR(10) NOT NULL,
    MaChiNhanh CHAR(10) NOT NULL, -- MỚI: Đơn hàng thuộc chi nhánh nào
    CONSTRAINT FK_DH_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT FK_DH_CN FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh),
    CONSTRAINT CHK_DH_TRANGTHAI CHECK (TrangThai IN ('CHO XAC NHAN','DA XAC NHAN','DANG GIAO','HOAN THANH','HUY')),
    CONSTRAINT CHK_DH_NGAYGIAO CHECK (NgayGiao IS NULL OR NgayGiao >= NgayDat)
);

-- 9. CHITIETDONHANG
CREATE TABLE CHITIETDONHANG (
    MaDH CHAR(10),
    MaHoa CHAR(10),
    SoLuongBan NUMBER(5) NOT NULL,
    TongDonGia NUMBER(12,2) NOT NULL,
    GIATHANHTOAN NUMBER(12,2),
    CONSTRAINT PK_CT_DH PRIMARY KEY (MaDH, MaHoa),
    CONSTRAINT FK_CT_DH_DH FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH) ON DELETE CASCADE,
    CONSTRAINT FK_CT_DH_HOA FOREIGN KEY (MaHoa) REFERENCES HOA(MaHoa),
    CONSTRAINT CHK_CTDH_SOLUONG CHECK (SoLuongBan >= 1),
    CONSTRAINT CHK_CTDH_TONGDG CHECK (TongDonGia >= 0)
);

-- 10. DONNHAPHANG
CREATE TABLE DONNHAPHANG (
    MaDonNhapHang CHAR(10) PRIMARY KEY,
    NgayNhap DATE DEFAULT SYSDATE NOT NULL,
    MaNV CHAR(10) NOT NULL,
    CONSTRAINT FK_DNH_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

-- 11. CHITIETNHAPHANG
CREATE TABLE CHITIETNHAPHANG (
    MaDonNhapHang CHAR(10),
    MaHoa CHAR(10),
    SoLuongNhap NUMBER(5) NOT NULL,
    DonGiaNhap NUMBER(10,2) NOT NULL,
    CONSTRAINT PK_CT_NH PRIMARY KEY (MaDonNhapHang, MaHoa),
    CONSTRAINT FK_CT_NH_DNH FOREIGN KEY (MaDonNhapHang) REFERENCES DONNHAPHANG(MaDonNhapHang) ON DELETE CASCADE,
    CONSTRAINT FK_CT_NH_HOA FOREIGN KEY (MaHoa) REFERENCES HOA(MaHoa),
    CONSTRAINT CHK_CTNH_SOLUONG CHECK (SoLuongNhap >= 1),
    CONSTRAINT CHK_CTNH_DONGIANHAP CHECK (DonGiaNhap > 0)
);
